### ISSUE TITLE
Minor change to Everly.sql

### ISSUE THREAD

**Issue by hmeijer2** [ifeanyiokagbue/Everly#1]
In Everly.sql line 18 set the default value for the @Conditions parameter to '' empty instead of NULL (or else use COALESCE as appropriate further down).

**Comment by ifeanyiokagbue** [comment]
> In Everly.sql line 18 set the default value for the @conditions parameter to '' empty instead of NULL (or else use COALESCE as appropriate further down).

Thanks!
